<a href="https://colab.research.google.com/github/Camila28Lopez/Laboratorio09_IA_SIS420/blob/main/Lab09_IA_LopezCamachoCamilaSalome.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import os 
import numpy as np
import pandas  as pd
from google.colab import drive
from matplotlib import pyplot
from mpl_toolkits.mplot3d import Axes3D 
%matplotlib inline

In [65]:
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [66]:
data = pd.read_csv('/content/drive/MyDrive/Dataset/data_num.csv')
data.head()

laptop_ID  Company      Product   TypeName  Inches  \
0         1      1.0  MacBook Pro  Ultrabook    13.3   
1         2      1.0  Macbook Air  Ultrabook    13.3   
2         3      2.0       250 G6   Notebook    15.6   
3         4      1.0  MacBook Pro  Ultrabook    15.4   
4         5      1.0  MacBook Pro  Ultrabook    13.3   

                     ScreenResolution                         Cpu   Ram  \
0  IPS Panel Retina Display 2560x1600        Intel Core i5 2.3GHz   8.0   
1                            1440x900        Intel Core i5 1.8GHz   8.0   
2                   Full HD 1920x1080  Intel Core i5 7200U 2.5GHz   8.0   
3  IPS Panel Retina Display 2880x1800        Intel Core i7 2.7GHz  16.0   
4  IPS Panel Retina Display 2560x1600        Intel Core i5 3.1GHz   8.0   

   Memory                           Gpu  OpSys  Weight  Price_euros  
0   128.0  Intel Iris Plus Graphics 640  macOS    1.37      1339.69  
1   128.0        Intel HD Graphics 6000  macOS    1.34       898.94  
2   256.0         Intel HD Graphics 620  No OS    1.86       575.00  
3   512.0            AMD Radeon Pro 455  macOS    1.83      2537.45  
4   256.0  Intel Iris Plus Graphics 650  macOS    1.37      1803.60

In [67]:
data = data.dropna()
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48 entries, 0 to 49
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   laptop_ID         48 non-null     object 
 1   Company           48 non-null     float64
 2   Product           48 non-null     object 
 3   TypeName          48 non-null     object 
 4   Inches            48 non-null     float64
 5   ScreenResolution  48 non-null     object 
 6   Cpu               48 non-null     object 
 7   Ram               48 non-null     float64
 8   Memory            48 non-null     float64
 9   Gpu               48 non-null     object 
 10  OpSys             48 non-null     object 
 11  Weight            48 non-null     float64
 12  Price_euros       48 non-null     float64
dtypes: float64(6), object(7)
memory usage: 5.2+ KB


In [68]:
X = data[[ 'Company', 'Inches', 'Ram', 'Memory','Weight']].to_numpy()
X

array([[1.000e+00, 1.330e+01, 8.000e+00, 1.280e+02, 1.370e+00],
       [1.000e+00, 1.330e+01, 8.000e+00, 1.280e+02, 1.340e+00],
       [2.000e+00, 1.560e+01, 8.000e+00, 2.560e+02, 1.860e+00],
       [1.000e+00, 1.540e+01, 1.600e+01, 5.120e+02, 1.830e+00],
       [1.000e+00, 1.330e+01, 8.000e+00, 2.560e+02, 1.370e+00],
       [3.000e+00, 1.560e+01, 4.000e+00, 5.000e+02, 2.100e+00],
       [1.000e+00, 1.540e+01, 1.600e+01, 2.560e+02, 2.040e+00],
       [1.000e+00, 1.330e+01, 8.000e+00, 2.560e+02, 1.340e+00],
       [4.000e+00, 1.400e+01, 1.600e+01, 5.120e+02, 1.300e+00],
       [3.000e+00, 1.400e+01, 8.000e+00, 2.560e+02, 1.600e+00],
       [2.000e+00, 1.560e+01, 4.000e+00, 5.000e+02, 1.860e+00],
       [2.000e+00, 1.560e+01, 4.000e+00, 5.000e+02, 1.860e+00],
       [1.000e+00, 1.540e+01, 1.600e+01, 2.560e+02, 1.830e+00],
       [5.000e+00, 1.560e+01, 4.000e+00, 2.560e+02, 2.200e+00],
       [1.000e+00, 1.330e+01, 8.000e+00, 2.560e+02, 1.370e+00],
       [5.000e+00, 1.560e+01, 8.000e+00,

In [69]:
y = data['Price_euros'].to_numpy()
y

array([1339.69,  898.94,  575.  , 2537.45, 1803.6 ,  400.  , 2139.97,
       1158.7 , 1495.  ,  770.  ,  393.9 ,  344.99, 2439.97,  498.9 ,
       1518.55,  745.  , 2858.  ,  499.  ,  979.  ,  191.9 ,  999.  ,
        258.  ,  819.  ,  659.  ,  418.64, 1099.  ,  800.  , 1298.  ,
        896.  ,  199.  ,  439.  , 1869.  ,  998.  ,  249.  ,  367.  ,
        979.  ,  488.69,  879.  ,  389.  , 1499.  ,  522.99,  682.  ,
        999.  , 1419.  ,  369.  , 1299.  ,  639.  ,  466.  ])

In [70]:
def  featureNormalize(X):
    X_norm = X.copy()
    mu = np.zeros(X.shape[1])
    sigma = np.zeros(X.shape[1])

    mu = np.mean(X, axis = 0)
    sigma = np.std(X, axis = 0)
    X_norm = (X - mu) / sigma
    
    return X_norm, mu, sigma

In [71]:
X_norm, mu, sigma = featureNormalize(X)

print(X)
print('Media calculada:', mu)
print('Desviación estandar calculada:', sigma)
print(X_norm)

[[1.000e+00 1.330e+01 8.000e+00 1.280e+02 1.370e+00]
 [1.000e+00 1.330e+01 8.000e+00 1.280e+02 1.340e+00]
 [2.000e+00 1.560e+01 8.000e+00 2.560e+02 1.860e+00]
 [1.000e+00 1.540e+01 1.600e+01 5.120e+02 1.830e+00]
 [1.000e+00 1.330e+01 8.000e+00 2.560e+02 1.370e+00]
 [3.000e+00 1.560e+01 4.000e+00 5.000e+02 2.100e+00]
 [1.000e+00 1.540e+01 1.600e+01 2.560e+02 2.040e+00]
 [1.000e+00 1.330e+01 8.000e+00 2.560e+02 1.340e+00]
 [4.000e+00 1.400e+01 1.600e+01 5.120e+02 1.300e+00]
 [3.000e+00 1.400e+01 8.000e+00 2.560e+02 1.600e+00]
 [2.000e+00 1.560e+01 4.000e+00 5.000e+02 1.860e+00]
 [2.000e+00 1.560e+01 4.000e+00 5.000e+02 1.860e+00]
 [1.000e+00 1.540e+01 1.600e+01 2.560e+02 1.830e+00]
 [5.000e+00 1.560e+01 4.000e+00 2.560e+02 2.200e+00]
 [1.000e+00 1.330e+01 8.000e+00 2.560e+02 1.370e+00]
 [5.000e+00 1.560e+01 8.000e+00 2.560e+02 2.200e+00]
 [1.000e+00 1.540e+01 1.600e+01 5.120e+02 1.830e+00]
 [6.000e+00 1.560e+01 8.000e+00 1.000e+03 2.200e+00]
 [5.000e+00 1.330e+01 8.000e+00 1.280e+02 1.22

In [72]:
m, n = X.shape
X_ready = np.concatenate([np.ones((m, 1)), X_norm], axis=1)

In [73]:
def calcularCosto(X, y, theta):
    m = y.size
    J = 0
    h = np.dot(X, theta)
    # print(h)
    J = (1/(2 * m)) * np.sum(np.square(np.dot(X, theta) - y))
    return J
   


In [74]:
# theta=np.array([0.1, 1.0, 0.1, 0.1, 1.0, 0.1])
# theta = np.random.rand(6)
theta = np.zeros(6)
JJ = calcularCosto(X_ready, y, theta)
print(f"con theta:{ theta } se obtiene un costo de: {JJ}")

con theta:[0. 0. 0. 0. 0. 0.] se obtiene un costo de: 650531.3115874999


In [75]:
def calcularDescensoGradiente(X, y, theta, alpha, numero_iteraciones):
      m = y.shape[0]
      theta = theta.copy()
      J_historico = []

      for i in range(numero_iteraciones):
        theta = theta - (alpha / m) * (np.dot(X, theta) - y).dot(X)
        J_historico.append(calcularCosto(X, y, theta))
      return theta, J_historico


In [76]:
theta = np.zeros(6)

num_ite = 100000
alpha = 0.001

theta, J_historico = calcularDescensoGradiente(X_ready, y, theta, alpha, num_ite)
print(f"los valores de theta calculados son: { theta }")
print(f"con un costo de: { J_historico[-1]} ")

los valores de theta calculados son: [ 949.70583333 -164.3127857  -140.90115727  530.36088044  -43.22719368
  154.59279955]
con un costo de: 34529.532330364054 


In [77]:
y_pred = np.dot([1, 3, 15.6, 8, 256, 2.2], theta)
print(y_pred)

-8224.460956265724


In [78]:
def CalcularthetaEcuacionNormal(X, y):
    theta = np.zeros(X.shape[1])
    theta = np.dot(np.dot(np.linalg.inv(np.dot(X.T,X)),X.T),y)
    return theta

In [79]:
X_ren = np.concatenate([np.ones((m, 1)), X], axis=1)


In [80]:
theta = CalcularthetaEcuacionNormal(X_ren, y);
print(f"los valores de theta calculados son: { theta }")

los valores de theta calculados son: [ 1.26410455e+03 -9.42737875e+01 -1.04603178e+02  1.32162475e+02
 -1.17423519e-01  3.08666655e+02]


In [83]:
X_array = [1, 3, 15.6, 8, 256, 2.2]
price = np.dot(X_array, theta)

print('Precio de un laptop: {:.0f}'.format(price))

Precio de un laptop: 1056
